Feature group keep
IgorOsiyuk/iTechArt-Laba_front pull request #12
Opened 2021-05-10 11:23 UTC by IgorOsiyuk

![image](https://user-images.githubusercontent.com/68943103/117651312-7c189d80-b19a-11eb-9b6f-690b332176d4.png)
add a button that opens a modal window where the user is able to choose keeps

![image](https://user-images.githubusercontent.com/68943103/117651217-60ad9280-b19a-11eb-8b7a-57c14f55a706.png)
create the feature that allows choose keeps for group up

![image](https://user-images.githubusercontent.com/68943103/117651487-aa967880-b19a-11eb-9d3a-8890a7719fd9.png)
Set up a button for saving user's choice. App show this button only for 2 and more chosen keeps

![image](https://user-images.githubusercontent.com/68943103/117651670-e3365200-b19a-11eb-854b-70b322ba8703.png)
create a modal window where user can print the name of his new folder

![image](https://user-images.githubusercontent.com/68943103/117651812-0bbe4c00-b19b-11eb-9e22-694002306db4.png)
create folders block and current block of folder that contains keeps.

![image](https://user-images.githubusercontent.com/68943103/117651923-36a8a000-b19b-11eb-8646-3bcd4a4ce814.png)
user can't drag keeps in folders

2021-05-20 10:59 UTC, vladkravc requested changes

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/Keep.jsx
> +import React, { useEffect, useRef } from "react";
you imports from 'react' twice

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/Keep.jsx
> +     z-index: ${!isGrouping ? "auto" : "999"};
create an object in theme to indicate elevation

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +  });
you can just use string for it

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +    });
`setFolderTitle(value)`

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +        let semiArr = [...chosenKeepsList];
use `const` instead

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +              });
setFolderTitle("")

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +      if (chosenKeepsList.length >= 1) {
`if (chosenKeepsList.length)`

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +            return;
no need return here

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolder.jsx
> +export const FolderBlock = styled.div`
new line

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolder.jsx
> +     z-index: ${isOpen ? "-22" : "1"};
what is that magic number? -22

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolder.jsx
> +  const [isChangedTitle, setChangedTitle] = useState(folderTitle.title);
incorrect name  is predict that it boolean value

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolderList.jsx
> +  /* padding: 16px; */
comments?

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolderList.jsx
> +    margin-bottom: 16px;
you can write it as 1 margin

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolderList.jsx
> +  if (!groupKeeps || groupKeeps.length === 0) {
`if (!groupKeeps || !groupKeeps.length)`

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsList.jsx
> +  if (!keepList || keepList.length === 0) {
`!keepList.length`

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/keeps/KeepsList.jsx
> +            draggable={isGrouping ? false : true}
`draggable={!isGrouping}`

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/pages/Keeps.jsx
> +        (!groupKeeps || groupKeeps.length === 0) ? (
```
!unGroupKeeps.length
!groupKeeps.length
```

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/components/shared/theme.jsx
> +    secondary: "#e0e0e0",
why are they similar?

2021-05-20 10:59 UTC, vladkravc commented on google_keeps/src/redux/action/user.jsx
> +
You can move action creators in separate file

2021-05-20 12:36 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +     z-index: ${!isGrouping ? "auto" : "999"};
- [+]

2021-05-20 12:38 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +  });
- [+]

2021-05-20 12:39 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +              });
- [+]

2021-05-20 12:59 UTC, IgorOsiyuk commented on google_keeps/src/components/shared/theme.jsx
> +    secondary: "#e0e0e0",
- [+]

2021-05-20 12:59 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Keeps.jsx
> +        (!groupKeeps || groupKeeps.length === 0) ? (
- [+]

2021-05-20 12:59 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsList.jsx
> +  if (!keepList || keepList.length === 0) {
- [+]

2021-05-20 13:00 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolderList.jsx
> +  /* padding: 16px; */
- [+]  
- remove comments but block don't remove.

2021-05-20 13:00 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolder.jsx
> +  const [isChangedTitle, setChangedTitle] = useState(folderTitle.title);
- [+]

2021-05-20 13:00 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolder.jsx
> +     z-index: ${isOpen ? "-22" : "1"};
- [+]

2021-05-20 13:00 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsFolder/KeepsFolder.jsx
> +export const FolderBlock = styled.div`
- [+]

2021-05-20 13:01 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +            return;
- [+]

2021-05-20 13:10 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsContent.jsx
> +      if (chosenKeepsList.length >= 1) {
that feature needs me to understand what type of action should app does.
If user click on "add to folder" btn then I allow him to choose 1 or more cards,
If user click on 'group keeps' btn then I allow him to choose 2 or more cards , but not least

2021-05-21 07:38 UTC, IgorOsiyuk commented on google_keeps/src/redux/action/user.jsx
> +
- [+]

2021-06-09 12:27 UTC, melonholy approved these changes

2021-06-14 06:07 UTC, merged