Recycle page
IgorOsiyuk/iTechArt-Laba_front pull request #13
Opened 2021-05-18 13:52 UTC by IgorOsiyuk

create new page which contains list of keeps that was removed from main board 
![image](https://user-images.githubusercontent.com/68943103/118663048-288cfc00-b7f9-11eb-9068-86d2e58578bd.png)

create sidebar for change application pages 
![image](https://user-images.githubusercontent.com/68943103/118663181-465a6100-b7f9-11eb-896d-979e2c9530c9.png)
also moved button logout into sidebar and rewrite it for a separate component

2021-06-09 12:32 UTC, melonholy requested changes

2021-06-09 12:32 UTC, melonholy commented on google_keeps/src/components/RecycleComponent/RecycleBlock.jsx
> +  }, [listOfKeeps]);
Why do you need extra local state?

2021-06-09 12:32 UTC, melonholy commented on google_keeps/src/components/pages/Keeps.jsx
> +          (!groupKeeps || !groupKeeps.length) ? (
i suggest to move it in separate variable

2021-06-14 06:17 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Keeps.jsx
> +          (!groupKeeps || !groupKeeps.length) ? (
- [+]

2021-06-14 06:26 UTC, IgorOsiyuk commented on google_keeps/src/components/RecycleComponent/RecycleBlock.jsx
> +  }, [listOfKeeps]);
- [+]
removed unnecessary state and change it to checking props were got by components

2021-06-18 11:16 UTC, melonholy approved these changes

2021-06-19 11:19 UTC, merged