Create Home page
IgorOsiyuk/iTechArt-Laba_front pull request #2
Opened 2021-04-16 13:28 UTC by IgorOsiyuk

create redux store
action and reducer for login 
for Authorized user show the main page as a Keep 
![image](https://user-images.githubusercontent.com/68943103/115031324-b14e0a80-9ed0-11eb-8b53-c3b6f35f06c7.png)

for Unauthorized user show the main page  with buttons "Registration" "Login" 
![image](https://user-images.githubusercontent.com/68943103/115031375-c165ea00-9ed0-11eb-8b1d-d2e6f00cc65c.png)

2021-04-19 10:35 UTC, melonholy requested changes

2021-04-19 10:35 UTC, melonholy commented on google_keeps/src/redux/action/types.jsx
> +export const LOGIN_USER = "LOGIN_USER";
new line

2021-04-19 10:35 UTC, melonholy commented on google_keeps/src/components/pages/Main.jsx
> +  const isLogin = useSelector((state) => state.auth.isLogin);
params in useSelector moving in separate folder named `selectors`

2021-04-19 10:35 UTC, melonholy commented on google_keeps/src/components/pages/Main.jsx
> +
Wrap it in useEffect

2021-04-21 10:33 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Main.jsx
> +  const isLogin = useSelector((state) => state.auth.isLogin);
- [+]

2021-04-21 10:33 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Main.jsx
> +
- [+]

2021-04-21 10:33 UTC, IgorOsiyuk commented on google_keeps/src/redux/action/types.jsx
> +export const LOGIN_USER = "LOGIN_USER";
- [+]

2021-04-21 14:26 UTC, IgorOsiyuk commented on google_keeps/src/redux/action/types.jsx
> +export const LOGIN_USER = "LOGIN_USER";
- [+]

2021-04-21 14:26 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Main.jsx
> +  const isLogin = useSelector((state) => state.auth.isLogin);
- [+]

2021-04-21 14:27 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Main.jsx
> +
- [+]

2021-04-23 10:30 UTC, melonholy approved these changes

2021-04-23 12:03 UTC, merged