Keeps page
IgorOsiyuk/iTechArt-Laba_front pull request #3
Opened 2021-04-19 15:03 UTC by IgorOsiyuk

create current keeps and list of keeps
also created request for get keeps from server
created actions and reducers for keeps request

![image](https://user-images.githubusercontent.com/68943103/115258217-769adb00-a139-11eb-830f-b25e0b2d8ee7.png)

2021-04-23 10:40 UTC, melonholy commented
![image](https://user-images.githubusercontent.com/36301981/115859895-66d10e80-a439-11eb-9041-3b3a8c544a28.png)
Weird placeholder names

2021-04-23 10:41 UTC, melonholy commented
Add. behavior of closing modal after click outside the modal

2021-04-23 10:44 UTC, melonholy commented
Cant check functionality 
![image](https://user-images.githubusercontent.com/36301981/115860277-f676bd00-a439-11eb-916a-59a1f4ca53a0.png)
You should change backend url for deployed version

2021-04-23 10:56 UTC, melonholy requested changes

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +  position: absolute;
You don't need position absolute for this

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +  animation-fill-mode:forwards;
spaces

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +  background-color: #fff;
You have theme color for this

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +const UpdateIcon = styled(Send)``;
Why do you need empty components?

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +    background-color: #dedede;
Theme color variable

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +  & + & {
???????

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/components/keeps/KeepsList.jsx
> +      {list.length !== 0 ? (
Just !list.length

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/redux/action/types.jsx
> +export const GET_USER_KEEPS = "GET_USER_KEEPS";
New line

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/redux/action/user.jsx
> +    );
no catch?

2021-04-23 10:56 UTC, melonholy commented on google_keeps/src/services/auth-header.jsx
> +import LocalStorageService from "./localStorage.service";
Services again)

2021-04-26 09:42 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  position: absolute;
- [+]

2021-04-26 09:43 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +const UpdateIcon = styled(Send)``;
removed it. I write it for future maybe I change something in this case
- [+]

2021-04-26 09:48 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +    background-color: #dedede;
- [+]

2021-04-26 09:51 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  & + & {
what's the question? ) 
I used "justify-content: flex-end" and each of the next button after first has margin-left 20px

2021-04-26 09:56 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsList.jsx
> +      {list.length !== 0 ? (
- [+]

2021-04-26 09:56 UTC, IgorOsiyuk commented on google_keeps/src/redux/action/types.jsx
> +export const GET_USER_KEEPS = "GET_USER_KEEPS";
- [+]

2021-04-26 09:57 UTC, IgorOsiyuk commented on google_keeps/src/services/auth-header.jsx
> +import LocalStorageService from "./localStorage.service";
- [+]

2021-04-26 11:34 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  position: absolute;
- [+]

2021-04-26 11:35 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  animation-fill-mode:forwards;
- [+]

2021-04-26 11:35 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  background-color: #fff;
- [+]

2021-04-26 12:14 UTC, IgorOsiyuk commented on google_keeps/src/redux/action/user.jsx
> +    );
I decided that add error functional when I'm going to do notification components

2021-04-29 11:15 UTC, melonholy requested changes

2021-04-29 11:15 UTC, melonholy commented on google_keeps/src/components/keeps/KeepsList.jsx
> +    </KeepListContainer>
Better write smth like this 
```
  if (!list.length)
    return (
      <KeepListContainer>
        <h2>у вас нет заметок</h2>
      </KeepListContainer>
    )

  return (
    <KeepListContainer>
      {list.map(item =>
        <Keep data={item} key={item._id} />
      )}
    </KeepListContainer>
  )
```

2021-04-29 11:15 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +    ${ControlPanel} {
Put new line between separate elements. Also check for all files

2021-04-29 11:15 UTC, melonholy commented on google_keeps/src/components/keeps/KeepsList.jsx
> +  margin: 0 -16px;
Why do you need negative margins?

2021-04-30 06:09 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsList.jsx
> +    </KeepListContainer>
- [+]

2021-04-30 06:18 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +    ${ControlPanel} {
- [+]

2021-04-30 06:18 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsList.jsx
> +  margin: 0 -16px;
- [+]

2021-04-30 08:50 UTC, melonholy approved these changes

2021-04-30 09:11 UTC, merged