Custom color for Keep
IgorOsiyuk/iTechArt-Laba_front pull request #7
Opened 2021-04-27 11:12 UTC by IgorOsiyuk

Create palette component
![image](https://user-images.githubusercontent.com/68943103/116231072-16232380-a761-11eb-95ed-12ddc816b444.png)
set up animation for palette component 
set up functional for change keep's color 
update PUT-request for keeps

2021-04-29 11:37 UTC, melonholy commented
Remove autocompletes 
![image](https://user-images.githubusercontent.com/36301981/116544880-59fc6100-a8f8-11eb-940b-4b7f2611e074.png)

2021-04-29 12:54 UTC, melonholy requested changes

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/PaletteComponent/PaletteForm.jsx
>    }, [color, changeColor]);
Remove use effecr

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/PaletteComponent/PaletteForm.jsx
> +  const [color, setColor] = useState();
remove local state

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/PaletteComponent/PaletteForm.jsx
> +      <PaletteBlock color={color} onChange={setColor} />
remove `color` prop and change `setColor` to `changeColor`

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +  const [bgColor, changeColor] = useState();
set `background` prop as default

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +
remove use effect

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +  const [isPalette, setPaletteState] = useState(false);
group all set states in one place

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/keeps/Keep.jsx
> +      <KeepForm bgColor={background} ref={formRef}>
change `background` to `bgColor `

2021-04-29 12:54 UTC, melonholy commented on google_keeps/src/components/keeps/KeepsList.jsx
> +  position:relative;
spaces)

2021-05-03 11:46 UTC, IgorOsiyuk commented on google_keeps/src/components/PaletteComponent/PaletteForm.jsx
>    }, [color, changeColor]);
- [+]

2021-05-03 11:46 UTC, IgorOsiyuk commented on google_keeps/src/components/PaletteComponent/PaletteForm.jsx
> +  const [color, setColor] = useState();
- [+]

2021-05-03 11:47 UTC, IgorOsiyuk commented on google_keeps/src/components/PaletteComponent/PaletteForm.jsx
> +      <PaletteBlock color={color} onChange={setColor} />
- [+]

2021-05-03 11:47 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  const [bgColor, changeColor] = useState();
- [+]

2021-05-03 11:47 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +
- [+]

2021-05-03 11:47 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +  const [isPalette, setPaletteState] = useState(false);
- [+]

2021-05-03 11:47 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/Keep.jsx
> +      <KeepForm bgColor={background} ref={formRef}>
- [+]

2021-05-03 11:47 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/KeepsList.jsx
> +  position:relative;
- [+]

2021-05-03 12:40 UTC, melonholy requested changes

2021-05-03 12:40 UTC, melonholy commented on google_keeps/src/Utils/hooks/debounce.jsx
> +export default function Debounce(value, delay) {
name hooks like useDebouce

2021-05-03 12:40 UTC, melonholy commented on google_keeps/src/Utils/hooks/debounce.jsx
> +  useEffect(() => {
space between

2021-05-03 12:40 UTC, melonholy commented on google_keeps/src/Utils/hooks/debounce.jsx
> +    return () => {
space

2021-05-03 12:40 UTC, melonholy commented on google_keeps/src/Utils/hooks/debounce.jsx
> +  return debouncedValue;
space

2021-05-03 12:40 UTC, melonholy commented on google_keeps/src/Utils/hooks/debounce.jsx
> +export default function Debounce(value, delay) {
also name utils folder with small case

2021-05-03 13:01 UTC, melonholy approved these changes

2021-05-03 13:08 UTC, merged