notification components
IgorOsiyuk/iTechArt-Laba_front pull request #8
Opened 2021-04-28 09:32 UTC by IgorOsiyuk

create and set up notifications for keep's request
![image](https://user-images.githubusercontent.com/68943103/116381061-36b0b380-a81d-11eb-942b-757dcc7c551f.png)
![image](https://user-images.githubusercontent.com/68943103/116381108-429c7580-a81d-11eb-9c79-4dd973caad61.png)

There are notifications for successful requests when we update, delete and post keeps
We also catch bad requests and show notification for this error in red

login: user@user.com
password: 1234567890

2021-04-29 13:07 UTC, melonholy requested changes

2021-04-29 13:07 UTC, melonholy commented on google_keeps/src/components/Notification/index.jsx
> +};
maybe you should name it like infoNotification and pass message as argument

2021-04-29 13:07 UTC, melonholy commented on google_keeps/src/components/Notification/index.jsx
> +};
name it like successNotification and pass message as argument

2021-04-29 13:07 UTC, melonholy commented on google_keeps/src/components/keeps/NewKeepForm.jsx
> +      res && setKeepData(defaultState);
hmmm is it required check?

2021-04-29 13:07 UTC, melonholy commented on google_keeps/src/components/pages/Keeps.jsx
> +      <Notification />
I suggest to move notification to the higher level of app

2021-04-29 13:07 UTC, melonholy commented on google_keeps/src/redux/reducers/user.jsx
> +    errorList: null,
probably errorList should be empty arr by default

2021-04-30 06:49 UTC, IgorOsiyuk commented on google_keeps/src/components/Notification/index.jsx
> +};
- [+]

2021-04-30 06:50 UTC, IgorOsiyuk commented on google_keeps/src/components/Notification/index.jsx
> +};
- [+]

2021-04-30 07:01 UTC, IgorOsiyuk commented on google_keeps/src/redux/reducers/user.jsx
> +    errorList: null,
- [+]

2021-04-30 07:02 UTC, IgorOsiyuk commented on google_keeps/src/components/pages/Keeps.jsx
> +      <Notification />
- [+] 
- I moved it to App component

2021-04-30 07:03 UTC, IgorOsiyuk commented on google_keeps/src/components/keeps/NewKeepForm.jsx
> +      res && setKeepData(defaultState);
that allows me to understand that post-request completed successfully and after that I clear all fields in my NewKeep form

2021-05-03 12:42 UTC, melonholy approved these changes

2021-05-03 13:09 UTC, merged